### ISSUE TITLE
installing scPPIN 

### ISSUE THREAD

**Issue by deevdevil88** [floklimm/scPPIN#1]
Hello,
sorry it isnt clear how best to install scPPIN . Do we install it via R or do we download the pre compiled source files and then point to the relevant directory for R to install it.

some  help would be appreciated!

Thanks,
Devika

**Comment by deevdevil88** [comment]
Nevermind i installed the package via source and that seemed to work. The only thing i was wondering, do i need to compile the solver for dapcstp eventhough the binaries are included in the package. if so what is the best way to do that, as the github page for dapcstp is sparse on instructions. 

Thanks,
Devika

**Comment by deevdevil88** [comment]
Sorry i will close this issue. I believe just using Make in the Makefile directory of dapcstp and removing the -static flag  in the makefile worked for me for Mac OS Catalin 10.15 to compile. So I will close the issue  now.

**Comment by floklimm** [comment]
You are correct: 
We provide binaries for Mac and Fedora but most likely it is best to compile _dapcstp_ yourself by executing the makefile.

Depending on your system you might have to adapt the makefile for _dapcstp_ Removing the `-static' flag is a common adaption that is necessary for successful compilation.
