### ISSUE TITLE
Error when running detectFunctionalModule

### ISSUE THREAD

**Issue by deevdevil88** [floklimm/scPPIN#4]
Hi,
I have been try to identify the most optimal Functional modules for all my cell types. however when i run the function detectfuncitonalmodule for some of my cell types , that have a high number of genes with pvalues (n=3000) , dapcstp gives an error as below
Error in if (is.numeric(v) && any(v < 0)) { : 
  missing value where TRUE/FALSE needed

is this because it couldnt find an optimal soultion at the particular FDR or is it to do with my data?

again the checksum test you have suggested returned 0.

Thanks some insight into what this error means in terms of identifying functional modules would be great!

Best,
Devika

**Comment by floklimm** [comment]
In general, it dapcstp should always be able to find an optimal solution (i.e., in `worst case' the optimal solution is just a single gene/protein with the lowest p-value).

The function `detectfuncitonalmodule' has been tested with >3000 p-values, so I don't think this is the problem.

I would suggest that you go through the stepwise tutorial `tutorial_scPPIN-stepwise.R`, this should allow you in more detail to identify which part of the code/data is the problem.

If you have identified the issue, maybe report back and we check how it can be avoided.

**Comment by deevdevil88** [comment]
i did the stepwise tutorial, and i think the problem is in the bit of the code that assigns the node weight.At some point when you shift the node scores to convert the MWST to PCST, its returns values of Inf for the node scores. Again perhaps following on with the problem of using multiple-test corrected pvalues i suppose. As i dint face this problem when i re-rain the analysis on the uncorrected pvalues.

**Comment by floklimm** [comment]
Okay, maybe run it with the uncorrected values for now.

But this part shouldn't usually have a problem with p-values >1.
