### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by utkinaira** [floklimm/scPPIN#5]
Hi!

I am struggling with installation of scPPIN and dapcstp libraries, usual way trough _devtools::install_github_ or cloning from github didn't work ("Error: Failed to install 'unknown package' from GitHub"). 
I would appreciate any help.

Best,
Irina

**Comment by floklimm** [comment]
Does it work when you download the files from GitHub and execute the files in 
scPPIN-library.R
?

Also, do you have a running version of dapcstp? I assume, that because of this binary file, the installation with devtools might fail. (But I might be mistaken)
